### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by LHBL2003**
For me it was position 6 because my USB bus runs faster.

### CODE REVIEW

**Review by cvanlabe — CHANGES_REQUESTED** [review]
What is meant with `bus14 <-> bus14` ?
Can you clarify or fix if this is by accident? :-)

Thanks for the improvement suggestions!

**Comment by LHBL2003** [comment]
Should fit now. Was double. Thank you

**Comment by grimmpp** [comment]
Cannot really remember why but there was for me an advantage for BA6 instead BA5. Having the same baudrate than FAM14 is also good.

**Comment by LHBL2003** [comment]
For me it's simple, I can't currently establish a connection with BA5 :D

**Review by cvanlabe — APPROVED** [review]

**Comment by cvanlabe** [comment]
> For me it's simple, I can't currently establish a connection with BA5 :D

Very strange... .

**Pull request merged**
